services:
  backend:
    image: leeryan2000/flashat-backend:latest  # ← pulled from hub
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - flashat-net

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}         
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: ${DB_NAME}           
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flashat-net

  redis:
    image: redis:alpine
    restart: always
    networks:
      - flashat-net

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    environment:
      RABBITMQ_USER: ${MQ_USER}
      RABBITMQ_PASS: ${MQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flashat-net


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/flashat.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/ssl/certs/cloudflare.pem:/etc/ssl/certs/cloudflare.pem:ro
      - /etc/ssl/private/cloudflare.key:/etc/ssl/private/cloudflare.key:ro
    restart: always
    depends_on:
      - backend
    networks:
      - flashat-net

networks:
  flashat-net:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: