services:
  backend:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/flashat-backend:latest  # ← pulled from hub
    restart: always
    env_file: .env
    networks:
      - flashat-net

  frontend:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/flashat-frontend:latest  # ← pulled from hub
    restart: always
    networks:
      - flashat-net

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}         
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: ${DB_NAME}           
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flashat-net

  redis:
    image: redis:alpine
    networks:
      - flashat-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/flashat.conf:/etc/nginx/conf.d/flashat.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - flashat-net

networks:
  flashat-net:
    driver: bridge

volumes:
  postgres_data: