/* DROP database IF EXISTS dev;
CREATE DATABASE dev; */


CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,

    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(60) NOT NULL,

    role VARCHAR(50) DEFAULT 'user',

    /* full_name VARCHAR(100), */
    /* is_active BOOLEAN DEFAULT TRUE, */

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
