// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthInternal_ValidateSession_FullMethodName = "/flashat.auth.v1.AuthInternal/ValidateSession"
	AuthInternal_GetFriendUIDs_FullMethodName   = "/flashat.auth.v1.AuthInternal/GetFriendUIDs"
)

// AuthInternalClient is the client API for AuthInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthInternal is exposed by the backend monolith over gRPC, on an
// internal-only port not reachable from the public internet (never proxied
// by nginx, never published in docker-compose). It lets other services
// (e.g. posts) reuse the monolith's Redis-session auth and friendship data
// without each service touching Redis/Postgres directly.
//
// Regenerate both consumers after editing this file:
//
//	make proto-gen
//
// which writes into backend/internal/genproto/authpb and
// posts/internal/genproto/authpb — see the root Makefile.
type AuthInternalClient interface {
	ValidateSession(ctx context.Context, in *ValidateSessionRequest, opts ...grpc.CallOption) (*ValidateSessionResponse, error)
	GetFriendUIDs(ctx context.Context, in *GetFriendUIDsRequest, opts ...grpc.CallOption) (*GetFriendUIDsResponse, error)
}

type authInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthInternalClient(cc grpc.ClientConnInterface) AuthInternalClient {
	return &authInternalClient{cc}
}

func (c *authInternalClient) ValidateSession(ctx context.Context, in *ValidateSessionRequest, opts ...grpc.CallOption) (*ValidateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateSessionResponse)
	err := c.cc.Invoke(ctx, AuthInternal_ValidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authInternalClient) GetFriendUIDs(ctx context.Context, in *GetFriendUIDsRequest, opts ...grpc.CallOption) (*GetFriendUIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendUIDsResponse)
	err := c.cc.Invoke(ctx, AuthInternal_GetFriendUIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthInternalServer is the server API for AuthInternal service.
// All implementations must embed UnimplementedAuthInternalServer
// for forward compatibility.
//
// AuthInternal is exposed by the backend monolith over gRPC, on an
// internal-only port not reachable from the public internet (never proxied
// by nginx, never published in docker-compose). It lets other services
// (e.g. posts) reuse the monolith's Redis-session auth and friendship data
// without each service touching Redis/Postgres directly.
//
// Regenerate both consumers after editing this file:
//
//	make proto-gen
//
// which writes into backend/internal/genproto/authpb and
// posts/internal/genproto/authpb — see the root Makefile.
type AuthInternalServer interface {
	ValidateSession(context.Context, *ValidateSessionRequest) (*ValidateSessionResponse, error)
	GetFriendUIDs(context.Context, *GetFriendUIDsRequest) (*GetFriendUIDsResponse, error)
	mustEmbedUnimplementedAuthInternalServer()
}

// UnimplementedAuthInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthInternalServer struct{}

func (UnimplementedAuthInternalServer) ValidateSession(context.Context, *ValidateSessionRequest) (*ValidateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSession not implemented")
}
func (UnimplementedAuthInternalServer) GetFriendUIDs(context.Context, *GetFriendUIDsRequest) (*GetFriendUIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendUIDs not implemented")
}
func (UnimplementedAuthInternalServer) mustEmbedUnimplementedAuthInternalServer() {}
func (UnimplementedAuthInternalServer) testEmbeddedByValue()                      {}

// UnsafeAuthInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthInternalServer will
// result in compilation errors.
type UnsafeAuthInternalServer interface {
	mustEmbedUnimplementedAuthInternalServer()
}

func RegisterAuthInternalServer(s grpc.ServiceRegistrar, srv AuthInternalServer) {
	// If the following call panics, it indicates UnimplementedAuthInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthInternal_ServiceDesc, srv)
}

func _AuthInternal_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInternalServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthInternal_ValidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInternalServer).ValidateSession(ctx, req.(*ValidateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthInternal_GetFriendUIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendUIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInternalServer).GetFriendUIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthInternal_GetFriendUIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInternalServer).GetFriendUIDs(ctx, req.(*GetFriendUIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthInternal_ServiceDesc is the grpc.ServiceDesc for AuthInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flashat.auth.v1.AuthInternal",
	HandlerType: (*AuthInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateSession",
			Handler:    _AuthInternal_ValidateSession_Handler,
		},
		{
			MethodName: "GetFriendUIDs",
			Handler:    _AuthInternal_GetFriendUIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
