name: Deploy Frontend (React)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'   # <--- Updated folder name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json # <--- Pointing to correct lock file

      - name: Install Dependencies
        working-directory: ./frontend  # <--- Run inside 'frontend' folder
        run: npm ci

      - name: Build Project
        working-directory: ./frontend
        run: npm run build
        # This creates 'frontend/dist'

      - name: Deploy to Nginx
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/dist/*"       # <--- Copy files from here
          target: "/var/www/flashat"
          strip_components: 2             # <--- Removes 'frontend/dist' (2 levels) so files land flat
          overwrite: true